<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table (tuple)*>
  <!ATTLIST table
            name  CDATA #REQUIRED
  >

  <!ELEMENT tuple (table|tuple|atom)*>
  <!ATTLIST tuple
            name  CDATA #IMPLIED
  >

  <!ELEMENT atom  (#PCDATA)*>
  <!ATTLIST atom
            name  CDATA #REQUIRED
            type  CDATA "text"
            size  CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    table           CreCreatorRef_tab
      integer         irn
      text short      NamFullName
      text short      SummaryData
      text long       BioLabel
      text short      NamSex
      text short      BioNationality
      text short      BioEthnicity
      text short      BioBirthDate
      text short      BioBirthPlace
      date            BioBirthEarliestDate
      date            BioBirthLatestDate
      text short      BioDeathDate
      text short      BioDeathPlace
      date            BioDeathEarliestDate
      date            BioDeathLatestDate
    end
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 5000 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5001 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5002 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5003 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5004 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5005 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5006 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5007 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5008 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5009 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5010 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5011 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5012 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5013 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5014 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5015 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5016 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5017 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5018 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5019 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5020 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5021 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5022 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5023 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5024 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5025 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5026 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5027 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5028 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>
        <atom name="BioDeathLatestDate">1926-10-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5029 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
        <atom name="NamFullName">Charles M. Russell</atom>
        <atom name="SummaryData">Russell, Charles M.</atom>
        <atom name="BioLabel">Charles M. Russell (1864-1926)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1864</atom>
        <atom name="BioBirthPlace">St. Louis, Missouri</atom>
        <atom name="BioBirthEarliestDate">1864-03-19</atom>
        <atom name="BioBirthLatestDate">1864-03-19</atom>
        <atom name="BioDeathDate">Oct. 24, 1926</atom>
        <atom name="BioDeathPlace">Great Falls, Montana</atom>
        <atom name="BioDeathEarliestDate">1926-10-24</atom>