<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    table           CreCreatorRef_tab
      integer         irn
      text short      NamFullName
      text short      SummaryData
      text long       BioLabel
      text short      NamSex
      text short      BioNationality
      text short      BioEthnicity
      text short      BioBirthDate
      text short      BioBirthPlace
      date            BioBirthEarliestDate
      date            BioBirthLatestDate
      text short      BioDeathDate
      text short      BioDeathPlace
      date            BioDeathEarliestDate
      date            BioDeathLatestDate
    end
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 3000 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2798</atom>
        <atom name="NamFullName">Marsden Hartley</atom>
        <atom name="SummaryData">Hartley, Marsden</atom>
        <atom name="BioLabel">Marsden Hartley (1877-1943)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Jan. 4, 1877</atom>
        <atom name="BioBirthPlace">Lewiston, Maine</atom>
        <atom name="BioBirthEarliestDate">1877-01-04</atom>
        <atom name="BioBirthLatestDate">1877-01-04</atom>
        <atom name="BioDeathDate">Sep. 2, 1943</atom>
        <atom name="BioDeathPlace">Ellsworth, Maine</atom>
        <atom name="BioDeathEarliestDate">1943-09-02</atom>
        <atom name="BioDeathLatestDate">1943-09-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3001 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2798</atom>
        <atom name="NamFullName">Marsden Hartley</atom>
        <atom name="SummaryData">Hartley, Marsden</atom>
        <atom name="BioLabel">Marsden Hartley (1877-1943)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Jan. 4, 1877</atom>
        <atom name="BioBirthPlace">Lewiston, Maine</atom>
        <atom name="BioBirthEarliestDate">1877-01-04</atom>
        <atom name="BioBirthLatestDate">1877-01-04</atom>
        <atom name="BioDeathDate">Sep. 2, 1943</atom>
        <atom name="BioDeathPlace">Ellsworth, Maine</atom>
        <atom name="BioDeathEarliestDate">1943-09-02</atom>
        <atom name="BioDeathLatestDate">1943-09-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3002 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2798</atom>
        <atom name="NamFullName">Marsden Hartley</atom>
        <atom name="SummaryData">Hartley, Marsden</atom>
        <atom name="BioLabel">Marsden Hartley (1877-1943)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Jan. 4, 1877</atom>
        <atom name="BioBirthPlace">Lewiston, Maine</atom>
        <atom name="BioBirthEarliestDate">1877-01-04</atom>
        <atom name="BioBirthLatestDate">1877-01-04</atom>
        <atom name="BioDeathDate">Sep. 2, 1943</atom>
        <atom name="BioDeathPlace">Ellsworth, Maine</atom>
        <atom name="BioDeathEarliestDate">1943-09-02</atom>
        <atom name="BioDeathLatestDate">1943-09-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3003 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2798</atom>
        <atom name="NamFullName">Marsden Hartley</atom>
        <atom name="SummaryData">Hartley, Marsden</atom>
        <atom name="BioLabel">Marsden Hartley (1877-1943)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Jan. 4, 1877</atom>
        <atom name="BioBirthPlace">Lewiston, Maine</atom>
        <atom name="BioBirthEarliestDate">1877-01-04</atom>
        <atom name="BioBirthLatestDate">1877-01-04</atom>
        <atom name="BioDeathDate">Sep. 2, 1943</atom>
        <atom name="BioDeathPlace">Ellsworth, Maine</atom>
        <atom name="BioDeathEarliestDate">1943-09-02</atom>
        <atom name="BioDeathLatestDate">1943-09-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3004 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2798</atom>
        <atom name="NamFullName">Marsden Hartley</atom>
        <atom name="SummaryData">Hartley, Marsden</atom>
        <atom name="BioLabel">Marsden Hartley (1877-1943)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Jan. 4, 1877</atom>
        <atom name="BioBirthPlace">Lewiston, Maine</atom>
        <atom name="BioBirthEarliestDate">1877-01-04</atom>
        <atom name="BioBirthLatestDate">1877-01-04</atom>
        <atom name="BioDeathDate">Sep. 2, 1943</atom>
        <atom name="BioDeathPlace">Ellsworth, Maine</atom>
        <atom name="BioDeathEarliestDate">1943-09-02</atom>
        <atom name="BioDeathLatestDate">1943-09-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3005 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2798</atom>
        <atom name="NamFullName">Marsden Hartley</atom>
        <atom name="SummaryData">Hartley, Marsden</atom>
        <atom name="BioLabel">Marsden Hartley (1877-1943)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Jan. 4, 1877</atom>
        <atom name="BioBirthPlace">Lewiston, Maine</atom>
        <atom name="BioBirthEarliestDate">1877-01-04</atom>
        <atom name="BioBirthLatestDate">1877-01-04</atom>
        <atom name="BioDeathDate">Sep. 2, 1943</atom>
        <atom name="BioDeathPlace">Ellsworth, Maine</atom>
        <atom name="BioDeathEarliestDate">1943-09-02</atom>
        <atom name="BioDeathLatestDate">1943-09-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3006 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1763</atom>
        <atom name="NamFullName">William Stanley Haseltine</atom>
        <atom name="SummaryData">Haseltine, William Stanley</atom>
        <atom name="BioLabel">William Stanley Haseltine (1835-1900)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1835</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1835</atom>
        <atom name="BioBirthLatestDate">1835</atom>
        <atom name="BioDeathDate">1900</atom>
        <atom name="BioDeathPlace">Rome, Italy</atom>
        <atom name="BioDeathEarliestDate">1900</atom>
        <atom name="BioDeathLatestDate">1900</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3007 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
        <atom name="NamFullName">Herbert Haseltine</atom>
        <atom name="SummaryData">Haseltine, Herbert</atom>
        <atom name="BioLabel">Herbert Haseltine (1877-1962)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1877</atom>
        <atom name="BioBirthPlace">Rome, Italy</atom>
        <atom name="BioBirthEarliestDate">1877</atom>
        <atom name="BioBirthLatestDate">1877</atom>
        <atom name="BioDeathDate">1962</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">1962</atom>
        <atom name="BioDeathLatestDate">1962</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
        <atom name="NamFullName">Valsuani Fondeurs</atom>
        <atom name="SummaryData">Valsuani Fondeurs</atom>
        <atom name="BioLabel">Valsuani Fondeurs</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3008 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
        <atom name="NamFullName">Herbert Haseltine</atom>
        <atom name="SummaryData">Haseltine, Herbert</atom>
        <atom name="BioLabel">Herbert Haseltine (1877-1962)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1877</atom>
        <atom name="BioBirthPlace">Rome, Italy</atom>
        <atom name="BioBirthEarliestDate">1877</atom>
        <atom name="BioBirthLatestDate">1877</atom>
        <atom name="BioDeathDate">1962</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">1962</atom>
        <atom name="BioDeathLatestDate">1962</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
        <atom name="NamFullName">Valsuani Fondeurs</atom>
        <atom name="SummaryData">Valsuani Fondeurs</atom>
        <atom name="BioLabel">Valsuani Fondeurs</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3009 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
        <atom name="NamFullName">Herbert Haseltine</atom>
        <atom name="SummaryData">Haseltine, Herbert</atom>
        <atom name="BioLabel">Herbert Haseltine (1877-1962)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1877</atom>
        <atom name="BioBirthPlace">Rome, Italy</atom>
        <atom name="BioBirthEarliestDate">1877</atom>
        <atom name="BioBirthLatestDate">1877</atom>
        <atom name="BioDeathDate">1962</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">1962</atom>
        <atom name="BioDeathLatestDate">1962</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
        <atom name="NamFullName">Valsuani Fondeurs</atom>
        <atom name="SummaryData">Valsuani Fondeurs</atom>
        <atom name="BioLabel">Valsuani Fondeurs</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3010 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
        <atom name="NamFullName">Herbert Haseltine</atom>
        <atom name="SummaryData">Haseltine, Herbert</atom>
        <atom name="BioLabel">Herbert Haseltine (1877-1962)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1877</atom>
        <atom name="BioBirthPlace">Rome, Italy</atom>
        <atom name="BioBirthEarliestDate">1877</atom>
        <atom name="BioBirthLatestDate">1877</atom>
        <atom name="BioDeathDate">1962</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">1962</atom>
        <atom name="BioDeathLatestDate">1962</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
        <atom name="NamFullName">Valsuani Fondeurs</atom>
        <atom name="SummaryData">Valsuani Fondeurs</atom>
        <atom name="BioLabel">Valsuani Fondeurs</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3011 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
        <atom name="NamFullName">Herbert Haseltine</atom>
        <atom name="SummaryData">Haseltine, Herbert</atom>
        <atom name="BioLabel">Herbert Haseltine (1877-1962)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1877</atom>
        <atom name="BioBirthPlace">Rome, Italy</atom>
        <atom name="BioBirthEarliestDate">1877</atom>
        <atom name="BioBirthLatestDate">1877</atom>
        <atom name="BioDeathDate">1962</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">1962</atom>
        <atom name="BioDeathLatestDate">1962</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
        <atom name="NamFullName">Valsuani Fondeurs</atom>
        <atom name="SummaryData">Valsuani Fondeurs</atom>
        <atom name="BioLabel">Valsuani Fondeurs</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3012 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
        <atom name="NamFullName">Herbert Haseltine</atom>
        <atom name="SummaryData">Haseltine, Herbert</atom>
        <atom name="BioLabel">Herbert Haseltine (1877-1962)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1877</atom>
        <atom name="BioBirthPlace">Rome, Italy</atom>
        <atom name="BioBirthEarliestDate">1877</atom>
        <atom name="BioBirthLatestDate">1877</atom>
        <atom name="BioDeathDate">1962</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">1962</atom>
        <atom name="BioDeathLatestDate">1962</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
        <atom name="NamFullName">Valsuani Fondeurs</atom>
        <atom name="SummaryData">Valsuani Fondeurs</atom>
        <atom name="BioLabel">Valsuani Fondeurs</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3013 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
        <atom name="NamFullName">Herbert Haseltine</atom>
        <atom name="SummaryData">Haseltine, Herbert</atom>
        <atom name="BioLabel">Herbert Haseltine (1877-1962)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1877</atom>
        <atom name="BioBirthPlace">Rome, Italy</atom>
        <atom name="BioBirthEarliestDate">1877</atom>
        <atom name="BioBirthLatestDate">1877</atom>
        <atom name="BioDeathDate">1962</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">1962</atom>
        <atom name="BioDeathLatestDate">1962</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
        <atom name="NamFullName">Valsuani Fondeurs</atom>
        <atom name="SummaryData">Valsuani Fondeurs</atom>
        <atom name="BioLabel">Valsuani Fondeurs</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3014 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
        <atom name="NamFullName">Herbert Haseltine</atom>
        <atom name="SummaryData">Haseltine, Herbert</atom>
        <atom name="BioLabel">Herbert Haseltine (1877-1962)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1877</atom>
        <atom name="BioBirthPlace">Rome, Italy</atom>
        <atom name="BioBirthEarliestDate">1877</atom>
        <atom name="BioBirthLatestDate">1877</atom>
        <atom name="BioDeathDate">1962</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">1962</atom>
        <atom name="BioDeathLatestDate">1962</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
        <atom name="NamFullName">Valsuani Fondeurs</atom>
        <atom name="SummaryData">Valsuani Fondeurs</atom>
        <atom name="BioLabel">Valsuani Fondeurs</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3015 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
        <atom name="NamFullName">Herbert Haseltine</atom>
        <atom name="SummaryData">Haseltine, Herbert</atom>
        <atom name="BioLabel">Herbert Haseltine (1877-1962)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1877</atom>
        <atom name="BioBirthPlace">Rome, Italy</atom>
        <atom name="BioBirthEarliestDate">1877</atom>
        <atom name="BioBirthLatestDate">1877</atom>
        <atom name="BioDeathDate">1962</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">1962</atom>
        <atom name="BioDeathLatestDate">1962</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
        <atom name="NamFullName">Valsuani Fondeurs</atom>
        <atom name="SummaryData">Valsuani Fondeurs</atom>
        <atom name="BioLabel">Valsuani Fondeurs</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3016 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
        <atom name="NamFullName">Herbert Haseltine</atom>
        <atom name="SummaryData">Haseltine, Herbert</atom>
        <atom name="BioLabel">Herbert Haseltine (1877-1962)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1877</atom>
        <atom name="BioBirthPlace">Rome, Italy</atom>
        <atom name="BioBirthEarliestDate">1877</atom>
        <atom name="BioBirthLatestDate">1877</atom>
        <atom name="BioDeathDate">1962</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">1962</atom>
        <atom name="BioDeathLatestDate">1962</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
        <atom name="NamFullName">Valsuani Fondeurs</atom>
        <atom name="SummaryData">Valsuani Fondeurs</atom>
        <atom name="BioLabel">Valsuani Fondeurs</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3017 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
        <atom name="NamFullName">Herbert Haseltine</atom>
        <atom name="SummaryData">Haseltine, Herbert</atom>
        <atom name="BioLabel">Herbert Haseltine (1877-1962)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1877</atom>
        <atom name="BioBirthPlace">Rome, Italy</atom>
        <atom name="BioBirthEarliestDate">1877</atom>
        <atom name="BioBirthLatestDate">1877</atom>
        <atom name="BioDeathDate">1962</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">1962</atom>
        <atom name="BioDeathLatestDate">1962</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
        <atom name="NamFullName">Valsuani Fondeurs</atom>
        <atom name="SummaryData">Valsuani Fondeurs</atom>
        <atom name="BioLabel">Valsuani Fondeurs</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3018 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
        <atom name="NamFullName">Herbert Haseltine</atom>
        <atom name="SummaryData">Haseltine, Herbert</atom>
        <atom name="BioLabel">Herbert Haseltine (1877-1962)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1877</atom>
        <atom name="BioBirthPlace">Rome, Italy</atom>
        <atom name="BioBirthEarliestDate">1877</atom>
        <atom name="BioBirthLatestDate">1877</atom>
        <atom name="BioDeathDate">1962</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">1962</atom>
        <atom name="BioDeathLatestDate">1962</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
        <atom name="NamFullName">Valsuani Fondeurs</atom>
        <atom name="SummaryData">Valsuani Fondeurs</atom>
        <atom name="BioLabel">Valsuani Fondeurs</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3019 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
        <atom name="NamFullName">Herbert Haseltine</atom>
        <atom name="SummaryData">Haseltine, Herbert</atom>
        <atom name="BioLabel">Herbert Haseltine (1877-1962)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1877</atom>
        <atom name="BioBirthPlace">Rome, Italy</atom>
        <atom name="BioBirthEarliestDate">1877</atom>
        <atom name="BioBirthLatestDate">1877</atom>
        <atom name="BioDeathDate">1962</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">1962</atom>
        <atom name="BioDeathLatestDate">1962</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
        <atom name="NamFullName">Valsuani Fondeurs</atom>
        <atom name="SummaryData">Valsuani Fondeurs</atom>
        <atom name="BioLabel">Valsuani Fondeurs</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3020 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
        <atom name="NamFullName">Herbert Haseltine</atom>
        <atom name="SummaryData">Haseltine, Herbert</atom>
        <atom name="BioLabel">Herbert Haseltine (1877-1962)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1877</atom>
        <atom name="BioBirthPlace">Rome, Italy</atom>
        <atom name="BioBirthEarliestDate">1877</atom>
        <atom name="BioBirthLatestDate">1877</atom>
        <atom name="BioDeathDate">1962</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">1962</atom>
        <atom name="BioDeathLatestDate">1962</atom>