<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table   (tuple)*>
  <!ATTLIST table
            name    CDATA #REQUIRED
  >

  <!ELEMENT tuple   (table|tuple|atom)*>
  <!ATTLIST tuple
            name    CDATA #IMPLIED
  >

  <!ELEMENT atom    (#PCDATA)*>
  <!ATTLIST atom
            name    CDATA #REQUIRED
            type    CDATA "text"
            size    CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    table           CreCreatorRef_tab
      integer         irn
      text short      NamFullName
      text short      SummaryData
      text long       BioLabel
      text short      NamSex
      text short      BioNationality
      text short      BioEthnicity
      text short      BioBirthDate
      text short      BioBirthPlace
      date            BioBirthEarliestDate
      date            BioBirthLatestDate
      text short      BioDeathDate
      text short      BioDeathPlace
      date            BioDeathEarliestDate
      date            BioDeathLatestDate
    end
  end
?>
<!-- Data -->
<table name="ecatalogue">
  <!-- Row 6000 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6001 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6002 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6003 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6004 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6005 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6006 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6007 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6008 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6009 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6010 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6011 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6012 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6013 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6014 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4875</atom>
        <atom name="NamFullName">Frederick Hess</atom>
        <atom name="SummaryData">Hess, Frederick</atom>
        <atom name="BioLabel">Frederick Hess</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6015 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">1514</atom>
        <atom name="NamFullName">Joseph John Stoner</atom>
        <atom name="SummaryData">Stoner, Joseph John</atom>
        <atom name="BioLabel">Joseph John Stoner (1829-1917)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1829</atom>
        <atom name="BioBirthPlace">Highspire, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1829</atom>
        <atom name="BioBirthLatestDate">1829</atom>
        <atom name="BioDeathDate">1917</atom>
        <atom name="BioDeathPlace">Berkeley, California</atom>
        <atom name="BioDeathEarliestDate">1917</atom>
        <atom name="BioDeathLatestDate">1917</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6016 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2035</atom>
        <atom name="NamFullName">Currier &amp; Ives</atom>
        <atom name="SummaryData">Currier &amp; Ives</atom>
        <atom name="BioLabel">Currier &amp; Ives</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6017 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
        <atom name="NamFullName">Unknown</atom>
        <atom name="SummaryData">Unknown</atom>
        <atom name="BioLabel">Unknown</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>