<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    table           CreCreatorRef_tab
      integer         irn
      text short      NamFullName
      text short      SummaryData
      text long       BioLabel
      text short      NamSex
      text short      BioNationality
      text short      BioEthnicity
      text short      BioBirthDate
      text short      BioBirthPlace
      date            BioBirthEarliestDate
      date            BioBirthLatestDate
      text short      BioDeathDate
      text short      BioDeathPlace
      date            BioDeathEarliestDate
      date            BioDeathLatestDate
    end
  end
?>
<!-- Data -->
<table name="ecatalogue">
   <!-- Row 1000 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1820</atom>
        <atom name="NamFullName">Grafton Tyler Brown</atom>
        <atom name="SummaryData">Brown, Grafton Tyler</atom>
        <atom name="BioLabel">Grafton Tyler Brown (1841-1918)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity">African-American</atom>
        <atom name="BioBirthDate">Feb. 22, 1841</atom>
        <atom name="BioBirthPlace">Harrisburg, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1841-02-22</atom>
        <atom name="BioBirthLatestDate">1841-02-22</atom>
        <atom name="BioDeathDate">Mar. 2, 1918</atom>
        <atom name="BioDeathPlace">St. Paul, Minnesota</atom>
        <atom name="BioDeathEarliestDate">1918-03-02</atom>
        <atom name="BioDeathLatestDate">1918-03-02</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">1941</atom>
        <atom name="NamFullName">Britton &amp; Co.</atom>
        <atom name="SummaryData">Britton &amp; Co.</atom>
        <atom name="BioLabel">Britton &amp; Co.</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4181</atom>
        <atom name="NamFullName">Charles Conrad Kuchel</atom>
        <atom name="SummaryData">Kuchel, Charles Conrad</atom>
        <atom name="BioLabel">Charles Conrad Kuchel (1820-1864)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1820</atom>
        <atom name="BioBirthPlace">Zweibrucken, Switzerland</atom>
        <atom name="BioBirthEarliestDate">1820</atom>
        <atom name="BioBirthLatestDate">1820</atom>
        <atom name="BioDeathDate">1864</atom>
        <atom name="BioDeathPlace">San Francisco, California</atom>
        <atom name="BioDeathEarliestDate">1864</atom>
        <atom name="BioDeathLatestDate">1864</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1001 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2855</atom>
        <atom name="NamFullName">Henry Kirke Brown</atom>
        <atom name="SummaryData">Brown, Henry Kirke</atom>
        <atom name="BioLabel">Henry Kirke Brown (1814-1886)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Feb. 24, 1814</atom>
        <atom name="BioBirthPlace">Leyden, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1814-02-24</atom>
        <atom name="BioBirthLatestDate">1814-02-24</atom>
        <atom name="BioDeathDate">July 10, 1886</atom>
        <atom name="BioDeathPlace">Newburgh, New York</atom>
        <atom name="BioDeathEarliestDate">1886-07-10</atom>
        <atom name="BioDeathLatestDate">1886-07-10</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">6302</atom>
        <atom name="NamFullName">The Artist's Foundry</atom>
        <atom name="SummaryData">The Artist's Foundry</atom>
        <atom name="BioLabel">The Artist's Foundry</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1002 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2855</atom>
        <atom name="NamFullName">Henry Kirke Brown</atom>
        <atom name="SummaryData">Brown, Henry Kirke</atom>
        <atom name="BioLabel">Henry Kirke Brown (1814-1886)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Feb. 24, 1814</atom>
        <atom name="BioBirthPlace">Leyden, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1814-02-24</atom>
        <atom name="BioBirthLatestDate">1814-02-24</atom>
        <atom name="BioDeathDate">July 10, 1886</atom>
        <atom name="BioDeathPlace">Newburgh, New York</atom>
        <atom name="BioDeathEarliestDate">1886-07-10</atom>
        <atom name="BioDeathLatestDate">1886-07-10</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">6302</atom>
        <atom name="NamFullName">The Artist's Foundry</atom>
        <atom name="SummaryData">The Artist's Foundry</atom>
        <atom name="BioLabel">The Artist's Foundry</atom>
        <atom name="NamSex"></atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1003 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2855</atom>
        <atom name="NamFullName">Henry Kirke Brown</atom>
        <atom name="SummaryData">Brown, Henry Kirke</atom>
        <atom name="BioLabel">Henry Kirke Brown (1814-1886)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Feb. 24, 1814</atom>
        <atom name="BioBirthPlace">Leyden, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1814-02-24</atom>
        <atom name="BioBirthLatestDate">1814-02-24</atom>
        <atom name="BioDeathDate">July 10, 1886</atom>
        <atom name="BioDeathPlace">Newburgh, New York</atom>
        <atom name="BioDeathEarliestDate">1886-07-10</atom>
        <atom name="BioDeathLatestDate">1886-07-10</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">5123</atom>
        <atom name="NamFullName">E. Gruet</atom>
        <atom name="SummaryData">E. Gruet</atom>
        <atom name="BioLabel">E. Gruet</atom>
        <atom name="NamSex">Unknown</atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1004 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4458</atom>
        <atom name="NamFullName">George de Forest Brush</atom>
        <atom name="SummaryData">Brush, George de Forest</atom>
        <atom name="BioLabel">George de Forest Brush (1854 or 1855-1941)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1854 or 1855</atom>
        <atom name="BioBirthPlace">Shelbyville, Tennessee</atom>
        <atom name="BioBirthEarliestDate">1854</atom>
        <atom name="BioBirthLatestDate">1855</atom>
        <atom name="BioDeathDate">Apr. 25, 1941</atom>
        <atom name="BioDeathPlace">Hanover, New Hampshire</atom>
        <atom name="BioDeathEarliestDate">1941-04-25</atom>
        <atom name="BioDeathLatestDate">1941-04-25</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1005 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2744</atom>
        <atom name="NamFullName">Dennis Miller Bunker</atom>
        <atom name="SummaryData">Bunker, Dennis Miller</atom>
        <atom name="BioLabel">Dennis Miller Bunker (1861-1890)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Nov. 6, 1861</atom>
        <atom name="BioBirthPlace">New York, New York</atom>
        <atom name="BioBirthEarliestDate">1861-11-06</atom>
        <atom name="BioBirthLatestDate">1861-11-06</atom>
        <atom name="BioDeathDate">Dec. 28, 1890</atom>
        <atom name="BioDeathPlace">Boston, Massachusetts</atom>
        <atom name="BioDeathEarliestDate">1890-12-28</atom>
        <atom name="BioDeathLatestDate">1890-12-28</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1006 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1914</atom>
        <atom name="NamFullName">Charles Burchfield</atom>
        <atom name="SummaryData">Burchfield, Charles</atom>
        <atom name="BioLabel">Charles Burchfield (1893-1967)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Apr. 9, 1893</atom>
        <atom name="BioBirthPlace">Ashtabula Harbor, Ohio</atom>
        <atom name="BioBirthEarliestDate">1893-04-09</atom>
        <atom name="BioBirthLatestDate">1893-04-09</atom>
        <atom name="BioDeathDate">Jan. 10, 1967</atom>
        <atom name="BioDeathPlace">Buffalo, New York</atom>
        <atom name="BioDeathEarliestDate">1967-01-10</atom>
        <atom name="BioDeathLatestDate">1967-01-10</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1007 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1914</atom>
        <atom name="NamFullName">Charles Burchfield</atom>
        <atom name="SummaryData">Burchfield, Charles</atom>
        <atom name="BioLabel">Charles Burchfield (1893-1967)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Apr. 9, 1893</atom>
        <atom name="BioBirthPlace">Ashtabula Harbor, Ohio</atom>
        <atom name="BioBirthEarliestDate">1893-04-09</atom>
        <atom name="BioBirthLatestDate">1893-04-09</atom>
        <atom name="BioDeathDate">Jan. 10, 1967</atom>
        <atom name="BioDeathPlace">Buffalo, New York</atom>
        <atom name="BioDeathEarliestDate">1967-01-10</atom>
        <atom name="BioDeathLatestDate">1967-01-10</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1008 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1914</atom>
        <atom name="NamFullName">Charles Burchfield</atom>
        <atom name="SummaryData">Burchfield, Charles</atom>
        <atom name="BioLabel">Charles Burchfield (1893-1967)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Apr. 9, 1893</atom>
        <atom name="BioBirthPlace">Ashtabula Harbor, Ohio</atom>
        <atom name="BioBirthEarliestDate">1893-04-09</atom>
        <atom name="BioBirthLatestDate">1893-04-09</atom>
        <atom name="BioDeathDate">Jan. 10, 1967</atom>
        <atom name="BioDeathPlace">Buffalo, New York</atom>
        <atom name="BioDeathEarliestDate">1967-01-10</atom>
        <atom name="BioDeathLatestDate">1967-01-10</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1009 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">5892</atom>
        <atom name="NamFullName">Horace Robbins Burdick</atom>
        <atom name="SummaryData">Burdick, Horace Robbins</atom>
        <atom name="BioLabel">Horace Robbins Burdick (1844-1942)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1844</atom>
        <atom name="BioBirthPlace">East Killingly, Connecticut</atom>
        <atom name="BioBirthEarliestDate">1844</atom>
        <atom name="BioBirthLatestDate">1844</atom>
        <atom name="BioDeathDate">1942</atom>
        <atom name="BioDeathPlace">Malden, Massachusetts</atom>
        <atom name="BioDeathEarliestDate">1942</atom>
        <atom name="BioDeathLatestDate">1942</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1010 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3630</atom>
        <atom name="NamFullName">James E. Butterworth</atom>
        <atom name="SummaryData">Butterworth, James E.</atom>
        <atom name="BioLabel">James E. Buttersworth (1817-1894)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1817</atom>
        <atom name="BioBirthPlace">London, England</atom>
        <atom name="BioBirthEarliestDate">1817</atom>
        <atom name="BioBirthLatestDate">1817</atom>
        <atom name="BioDeathDate">1894</atom>
        <atom name="BioDeathPlace">West Hoboken, New Jersey</atom>
        <atom name="BioDeathEarliestDate">1894</atom>
        <atom name="BioDeathLatestDate">1894</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2285</atom>
        <atom name="NamFullName">Eliphalet M. Brown Jr.</atom>
        <atom name="SummaryData">Brown, Eliphalet M., Jr.</atom>
        <atom name="BioLabel">Eliphalet M. Brown Jr. (1816-1886)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1816</atom>
        <atom name="BioBirthPlace">Newburyport, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1816</atom>
        <atom name="BioBirthLatestDate">1816</atom>
        <atom name="BioDeathDate">Jan. 23, 1886</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1886-01-23</atom>
        <atom name="BioDeathLatestDate">1886-01-23</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1011 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3630</atom>
        <atom name="NamFullName">James E. Butterworth</atom>
        <atom name="SummaryData">Butterworth, James E.</atom>
        <atom name="BioLabel">James E. Buttersworth (1817-1894)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1817</atom>
        <atom name="BioBirthPlace">London, England</atom>
        <atom name="BioBirthEarliestDate">1817</atom>
        <atom name="BioBirthLatestDate">1817</atom>
        <atom name="BioDeathDate">1894</atom>
        <atom name="BioDeathPlace">West Hoboken, New Jersey</atom>
        <atom name="BioDeathEarliestDate">1894</atom>
        <atom name="BioDeathLatestDate">1894</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1012 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3630</atom>
        <atom name="NamFullName">James E. Butterworth</atom>
        <atom name="SummaryData">Butterworth, James E.</atom>
        <atom name="BioLabel">James E. Buttersworth (1817-1894)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1817</atom>
        <atom name="BioBirthPlace">London, England</atom>
        <atom name="BioBirthEarliestDate">1817</atom>
        <atom name="BioBirthLatestDate">1817</atom>
        <atom name="BioDeathDate">1894</atom>
        <atom name="BioDeathPlace">West Hoboken, New Jersey</atom>
        <atom name="BioDeathEarliestDate">1894</atom>
        <atom name="BioDeathLatestDate">1894</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">3609</atom>
        <atom name="NamFullName">Lauchlan McKay</atom>
        <atom name="SummaryData">McKay, Lauchlan</atom>
        <atom name="BioLabel">Lauchlan McKay</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality"></atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate"></atom>
        <atom name="BioBirthPlace"></atom>
        <atom name="BioBirthEarliestDate"></atom>
        <atom name="BioBirthLatestDate"></atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1013 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3630</atom>
        <atom name="NamFullName">James E. Butterworth</atom>
        <atom name="SummaryData">Butterworth, James E.</atom>
        <atom name="BioLabel">James E. Buttersworth (1817-1894)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1817</atom>
        <atom name="BioBirthPlace">London, England</atom>
        <atom name="BioBirthEarliestDate">1817</atom>
        <atom name="BioBirthLatestDate">1817</atom>
        <atom name="BioDeathDate">1894</atom>
        <atom name="BioDeathPlace">West Hoboken, New Jersey</atom>
        <atom name="BioDeathEarliestDate">1894</atom>
        <atom name="BioDeathLatestDate">1894</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2884</atom>
        <atom name="NamFullName">Frances Flora Bond Palmer</atom>
        <atom name="SummaryData">Palmer, Frances Flora Bond</atom>
        <atom name="BioLabel">Frances Flora Bond Palmer (1812-1876)</atom>
        <atom name="NamSex">Female</atom>
        <atom name="BioNationality">British</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1812</atom>
        <atom name="BioBirthPlace">Leicester, England</atom>
        <atom name="BioBirthEarliestDate">1812</atom>
        <atom name="BioBirthLatestDate">1812</atom>
        <atom name="BioDeathDate">Aug. 20, 1876</atom>
        <atom name="BioDeathPlace">Brooklyn, New York</atom>
        <atom name="BioDeathEarliestDate">1876</atom>
        <atom name="BioDeathLatestDate">1876</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1014 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3630</atom>
        <atom name="NamFullName">James E. Butterworth</atom>
        <atom name="SummaryData">Butterworth, James E.</atom>
        <atom name="BioLabel">James E. Buttersworth (1817-1894)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1817</atom>
        <atom name="BioBirthPlace">London, England</atom>
        <atom name="BioBirthEarliestDate">1817</atom>
        <atom name="BioBirthLatestDate">1817</atom>
        <atom name="BioDeathDate">1894</atom>
        <atom name="BioDeathPlace">West Hoboken, New Jersey</atom>
        <atom name="BioDeathEarliestDate">1894</atom>
        <atom name="BioDeathLatestDate">1894</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2364</atom>
        <atom name="NamFullName">Charles Parsons</atom>
        <atom name="SummaryData">Parsons, Charles</atom>
        <atom name="BioLabel">Charles Parsons (1821-1910)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American, born England</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">May 8, 1821</atom>
        <atom name="BioBirthPlace">Rowland's Castle, Hampshire, England</atom>
        <atom name="BioBirthEarliestDate">1821-05-08</atom>
        <atom name="BioBirthLatestDate">1821-05-08</atom>
        <atom name="BioDeathDate">Nov. 9, 1910</atom>
        <atom name="BioDeathPlace">Brooklyn, New York</atom>
        <atom name="BioDeathEarliestDate">1910-11-09</atom>
        <atom name="BioDeathLatestDate">1910-11-09</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1015 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3630</atom>
        <atom name="NamFullName">James E. Butterworth</atom>
        <atom name="SummaryData">Butterworth, James E.</atom>
        <atom name="BioLabel">James E. Buttersworth (1817-1894)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1817</atom>
        <atom name="BioBirthPlace">London, England</atom>
        <atom name="BioBirthEarliestDate">1817</atom>
        <atom name="BioBirthLatestDate">1817</atom>
        <atom name="BioDeathDate">1894</atom>
        <atom name="BioDeathPlace">West Hoboken, New Jersey</atom>
        <atom name="BioDeathEarliestDate">1894</atom>
        <atom name="BioDeathLatestDate">1894</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2364</atom>
        <atom name="NamFullName">Charles Parsons</atom>
        <atom name="SummaryData">Parsons, Charles</atom>
        <atom name="BioLabel">Charles Parsons (1821-1910)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American, born England</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">May 8, 1821</atom>
        <atom name="BioBirthPlace">Rowland's Castle, Hampshire, England</atom>
        <atom name="BioBirthEarliestDate">1821-05-08</atom>
        <atom name="BioBirthLatestDate">1821-05-08</atom>
        <atom name="BioDeathDate">Nov. 9, 1910</atom>
        <atom name="BioDeathPlace">Brooklyn, New York</atom>
        <atom name="BioDeathEarliestDate">1910-11-09</atom>
        <atom name="BioDeathLatestDate">1910-11-09</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
        <atom name="NamFullName">Nathaniel Currier</atom>
        <atom name="SummaryData">Currier, Nathaniel</atom>
        <atom name="BioLabel">Nathaniel Currier (1813-1888)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 27, 1813</atom>
        <atom name="BioBirthPlace">Roxbury, Massachusetts</atom>
        <atom name="BioBirthEarliestDate">1813-03-27</atom>
        <atom name="BioBirthLatestDate">1813-03-27</atom>
        <atom name="BioDeathDate">Nov. 20, 1888</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1888-11-20</atom>
        <atom name="BioDeathLatestDate">1888-11-20</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 1016 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3630</atom>
        <atom name="NamFullName">James E. Butterworth</atom>
        <atom name="SummaryData">Butterworth, James E.</atom>
        <atom name="BioLabel">James E. Buttersworth (1817-1894)</atom>