<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    table           Group1
      integer         irn
    end
    text short      TitAccessionNo
    tuple           AccAccessionLotRef
      text long       AcqCreditLine
    end
    text long       WorAcmCollectionName
    table           CreCreatorRef_tab
      integer         irn
    end
    text long       TitMainTitle
    text long       TitParentTitle
    text long       CreRole_tab
    text long       CreType_tab
    text long       CreDateCreated_tab
    text short      MedFormat
    text long       MedMedium
    text short      MedObjectType
    text long       MedTechnique
    text long       MedType_tab
    text long       MedUnit_tab
    text long       MedUnitMetric_tab
    text long       MedValue_tab
    text long       MedValueMetric_tab
    text short      EdiEdition
    text long       RefCopyright_tab
    text long       ExhExhibitionRequirements
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 5000 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">70599</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.288</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Making a Cigarette (The Virginian)</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1911</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">12 5/8
9 5/8</atom>
    <atom name="MedValueMetric_tab">32.07
24.45</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.70599]</atom>
  </tuple>

  <!-- Row 5001 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">99407</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.295</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Bold Hunters Heavens! A Grizzly Bear-</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1907</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink and transparent watercolor over graphite underdrawing on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">7 1/2
12 1/4</atom>
    <atom name="MedValueMetric_tab">19.05
31.12</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.99407]</atom>
  </tuple>

  <!-- Row 5002 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">127434</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.296</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">I Beat You to It.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1908</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink, watercolor, and opaque watercolor on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">8
19 5/8</atom>
    <atom name="MedValueMetric_tab">20.32
49.85</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.127434]</atom>
  </tuple>

  <!-- Row 5003 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">60825</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.298</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Cyuse Bill</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1918</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">11 3/8
9 1/8</atom>
    <atom name="MedValueMetric_tab">28.89
23.18</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.60825]</atom>
  </tuple>

  <!-- Row 5004 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">73342</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.305.2</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Contrast in Artist's Salons--My Studio as Mother Thought</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1894</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink and ink wash over graphite underdrawing on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">7 1/2
8 1/2</atom>
    <atom name="MedValueMetric_tab">19.05
21.59</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.73342]</atom>
  </tuple>

  <!-- Row 5005 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">38709</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.310</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Dance! You Short-Horn Dance!</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1907</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink and transparent watercolor over graphite underdrawing on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">7 5/8
12 1/8</atom>
    <atom name="MedValueMetric_tab">19.37
30.8</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.38709]</atom>
  </tuple>

  <!-- Row 5006 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">2992</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.315</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Plummer's Men at Work</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1922</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink and graphite on paperboard</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">14 1/2
23 1/4</atom>
    <atom name="MedValueMetric_tab">36.83
59.06</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.2992]</atom>
  </tuple>

  <!-- Row 5007 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">14621</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.316</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Killing of Jules Reni by Slade</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1922</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink and graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">14
22</atom>
    <atom name="MedValueMetric_tab">35.56
55.88</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.14621]</atom>
  </tuple>

  <!-- Row 5008 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">87348</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.317</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Work on the Roundup</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1922</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink and graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">14
22</atom>
    <atom name="MedValueMetric_tab">35.56
55.88</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.87348]</atom>
  </tuple>

  <!-- Row 5009 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">127170</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.318</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Before the White Man Came</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1922</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink and graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">13 3/4
22 1/8</atom>
    <atom name="MedValueMetric_tab">34.93
56.2</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.127170]</atom>
  </tuple>

  <!-- Row 5010 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">14926</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.319.1</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Oñate's March into the New Mexican Country</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1922</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink and graphite on paperboard</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">14 3/8
22 5/8</atom>
    <atom name="MedValueMetric_tab">36.51
57.47</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.14926]</atom>
  </tuple>

  <!-- Row 5011 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">92728</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.319.2</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Rocky Mountain Trappers Driving Off Horses Stolen from California Mission</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1922</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink, opaque watercolor, and graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">14 3/8
22 3/4</atom>
    <atom name="MedValueMetric_tab">36.51
57.79</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.92728]</atom>
  </tuple>

  <!-- Row 5012 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">120854</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.320</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Bent's Fort on Arkansas River</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1922</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink and graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">14
22 1/8</atom>
    <atom name="MedValueMetric_tab">35.56
56.2</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.120854]</atom>
  </tuple>

  <!-- Row 5013 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">64369</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.321</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Cody's Fight with Yellow Hand</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1922</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink and graphite on paperboard</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">14 1/4
22 1/2</atom>
    <atom name="MedValueMetric_tab">36.2
57.15</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.64369]</atom>
  </tuple>

  <!-- Row 5014 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">30991</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.322</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">The Hide Trade of Old California</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1922</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink and graphite on paperboard</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">14 3/8
22 5/8</atom>
    <atom name="MedValueMetric_tab">36.51
57.47</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.30991]</atom>
  </tuple>

  <!-- Row 5015 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">30234</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.323</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Early Day White Buffalo Hunters</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1922</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink, opaque watercolor, and graphite on paper mounted on cardboard</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">14 1/8
22</atom>
    <atom name="MedValueMetric_tab">35.88
55.88</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.30234]</atom>
  </tuple>

  <!-- Row 5016 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">70753</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.370</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">[Composition study--landscape with figure on horseback]</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1920</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">6 1/2
10 3/8</atom>
    <atom name="MedValueMetric_tab">16.5
26.4</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.70753]</atom>
  </tuple>

  <!-- Row 5017 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">113307</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1961.371</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Amon G. Carter Collection</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Amon G. Carter Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">[Composition study--mounted figure holding rifle]</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1920</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">8 1/4
5 7/8</atom>
    <atom name="MedValueMetric_tab">20.96
14.92</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.113307]</atom>
  </tuple>

  <!-- Row 5018 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">5656</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1964.193.1</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of C. R. Smith</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">[Elk study]</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1912</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Graphite and watercolor on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">5
7</atom>
    <atom name="MedValueMetric_tab">12.7
17.78</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.5656]</atom>
  </tuple>

  <!-- Row 5019 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">23129</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1964.193.2</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of C. R. Smith</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1778</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">[Deer study]</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1912</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Graphite and watercolor on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">5
7</atom>
    <atom name="MedValueMetric_tab">12.7
17.78</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.23129]</atom>
  </tuple>

  <!-- Row 5020 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">72177</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1964.193.3</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of C. R. Smith</atom>
    </tuple>