<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    table           Group1
      integer         irn
    end
    text short      TitAccessionNo
    tuple           AccAccessionLotRef
      text long       AcqCreditLine
    end
    text long       WorAcmCollectionName
    table           CreCreatorRef_tab
      integer         irn
    end
    text long       TitMainTitle
    text long       TitParentTitle
    text long       CreRole_tab
    text long       CreType_tab
    text long       CreDateCreated_tab
    text short      MedFormat
    text long       MedMedium
    text short      MedObjectType
    text long       MedTechnique
    text long       MedType_tab
    text long       MedUnit_tab
    text long       MedUnitMetric_tab
    text long       MedValue_tab
    text long       MedValueMetric_tab
    text short      EdiEdition
    text long       RefCopyright_tab
    text long       ExhExhibitionRequirements
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 3000 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">90725</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1983.169</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2798</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Provincetown Abstraction</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1916</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Oil on composition board</atom>
    <atom name="MedObjectType">Paintings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">19 7/8
15 7/8</atom>
    <atom name="MedValueMetric_tab">50.48
40.32</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.90725]</atom>
  </tuple>

  <!-- Row 3001 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">51761</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1999.8</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2798</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">American Indian Symbols</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1914</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Oil on canvas</atom>
    <atom name="MedObjectType">Paintings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">39 3/16
39 3/16</atom>
    <atom name="MedValueMetric_tab">99.54
99.54</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.51761]</atom>
  </tuple>

  <!-- Row 3002 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">32933</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1990.1</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2798</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">A Range of Hills</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1930</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Metalpoint on paper prepared with white ground</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">10 3/4
14 7/8</atom>
    <atom name="MedValueMetric_tab">27.31
37.78</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© Yale Collection of American Literature, Beinecke Rare Book and Manuscript Library</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.32933]</atom>
  </tuple>

  <!-- Row 3003 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">83826</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1983.43</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Donald Marron Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2798</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Waxenstein</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1933</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">13 3/4
10 3/8
15 7/8
11 1/2</atom>
    <atom name="MedValueMetric_tab">34.93
26.35
40.32
29.21</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© Yale Collection of American Literature, Beinecke Rare Book and Manuscript Library</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.83826]</atom>
  </tuple>

  <!-- Row 3004 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">57238</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1967.191</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2798</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Earth Cooling</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1932</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Oil on cardboard mounted on masonite</atom>
    <atom name="MedObjectType">Paintings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">24 1/2
33 7/8</atom>
    <atom name="MedValueMetric_tab">62.23
86.04</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.57238]</atom>
  </tuple>

  <!-- Row 3005 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">31033</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1972.164</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Ruth Carter Stevenson</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2798</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Two Gulls</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1940</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Crayon and pastel on cardboard</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">10 1/4
26</atom>
    <atom name="MedValueMetric_tab">26.04
66.04</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© Yale Collection of American Literature, Beinecke Rare Book and Manuscript Library</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.31033]</atom>
  </tuple>

  <!-- Row 3006 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">32719</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1983.133</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1763</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Indian Rock with Two Fishermen, Narragansett Bay, Rhode Island</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1862-1863</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink, ink wash, and graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">15 1/8
22</atom>
    <atom name="MedValueMetric_tab">38.42
55.88</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.32719]</atom>
  </tuple>

  <!-- Row 3007 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">147499</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">2001.15.1</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Mr. and Mrs. Edward P. Bass in honor of Ruth Carter Stevenson on the occasion of the reopening of the Amon Carter Museum of American Art, 2001</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Aberdeen-Angus Bull: Black Knight of Auchterarder</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Cast by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1925</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Bronze</atom>
    <atom name="MedObjectType">Sculpture</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width
Depth
Base Height
Base Width
Base Depth</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">4 1/4
7 3/16
2 1/2
2 3/4
6
3 3/16</atom>
    <atom name="MedValueMetric_tab">10.8
18.3
6.4
7
15.3
8.1</atom>
    <atom name="EdiEdition">First set, 1/8 scale</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.147499]</atom>
  </tuple>

  <!-- Row 3008 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">147500</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">2001.15.2</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Mr. and Mrs. Edward P. Bass in honor of Ruth Carter Stevenson on the occasion of the reopening of the Amon Carter Museum of American Art, 2001</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Berkshire Boar: Highfield Royal Pygmalion</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Cast by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1925</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Bronze</atom>
    <atom name="MedObjectType">Sculpture</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width
Depth
Base Height
Base Width
Base Depth</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">2
4
1 1/2
2 13/16
3 3/8
1 15/16</atom>
    <atom name="MedValueMetric_tab">5.1
10.2
3.8
7.1
8.6
4.9</atom>
    <atom name="EdiEdition">First set, 1/8 scale</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.147500]</atom>
  </tuple>

  <!-- Row 3009 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">147501</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">2001.15.3</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Mr. and Mrs. Edward P. Bass in honor of Ruth Carter Stevenson on the occasion of the reopening of the Amon Carter Museum of American Art, 2001</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">The Chaser: Sergeant Murphy</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Cast by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1925</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Bronze</atom>
    <atom name="MedObjectType">Sculpture</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width
Depth
Base Height
Base Width
Base Depth</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">4 3/4
6 3/4
1 3/4
2 3/4
5 5/8
2 1/2</atom>
    <atom name="MedValueMetric_tab">12.1
17.1
4.5
7
14.3
6.4</atom>
    <atom name="EdiEdition">First set, 1/8 scale</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.147501]</atom>
  </tuple>

  <!-- Row 3010 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">147503</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">2001.15.4</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Mr. and Mrs. Edward P. Bass in honor of Ruth Carter Stevenson on the occasion of the reopening of the Amon Carter Museum of American Art, 2001</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Dairy Shorthorn Cow: Lily Charter 2ND</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Cast by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1925</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Bronze</atom>
    <atom name="MedObjectType">Sculpture</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width
Depth
Base Height
Base Width
Base Depth</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">4 1/16
6 1/4
2
2 3/4
5 13/16
2 13/16</atom>
    <atom name="MedValueMetric_tab">10.3
15.9
5.1
7
14.8
7.1</atom>
    <atom name="EdiEdition">First set, 1/8 scale</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.147503]</atom>
  </tuple>

  <!-- Row 3011 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">147504</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">2001.15.5</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Mr. and Mrs. Edward P. Bass in honor of Ruth Carter Stevenson on the occasion of the reopening of the Amon Carter Museum of American Art, 2001</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Hereford Bull: Twyford Fairy Boy</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Cast by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1925</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Bronze</atom>
    <atom name="MedObjectType">Sculpture</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width
Depth
Base Height
Base Width
Base Depth</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">4 1/4
6 5/8
2 1/2
2 3/4
6
3 3/16</atom>
    <atom name="MedValueMetric_tab">10.8
16.8
6.4
7
15.2
8.1</atom>
    <atom name="EdiEdition">First set, 1/8 scale</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.147504]</atom>
  </tuple>

  <!-- Row 3012 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">147505</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">2001.15.6</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Mr. and Mrs. Edward P. Bass in honor of Ruth Carter Stevenson on the occasion of the reopening of the Amon Carter Museum of American Art, 2001</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Lincoln Ram: Challenger</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Cast by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1925</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Bronze</atom>
    <atom name="MedObjectType">Sculpture</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width
Depth
Base Height
Base Width
Base Depth</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">2 1/2
3 5/8
1 1/2
2 13/16
3 3/16
1 5/8</atom>
    <atom name="MedValueMetric_tab">6.4
9.2
3.8
7.1
8.1
4.1</atom>
    <atom name="EdiEdition">First set, 1/8 scale</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.147505]</atom>
  </tuple>

  <!-- Row 3013 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">147506</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">2001.15.7</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Mr. and Mrs. Edward P. Bass in honor of Ruth Carter Stevenson on the occasion of the reopening of the Amon Carter Museum of American Art, 2001</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Lincoln Ram: Conqueror</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Cast by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1925</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Bronze</atom>
    <atom name="MedObjectType">Sculpture</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width
Depth
Base Height
Base Width
Base Depth</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">2 3/4
3 9/16
1 3/8
2 13/16
3 3/16
1 5/8</atom>
    <atom name="MedValueMetric_tab">7
9.1
3.5
7.1
8.1
4.1</atom>
    <atom name="EdiEdition">First set, 1/8 scale</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.147506]</atom>
  </tuple>

  <!-- Row 3014 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">147507</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">2001.15.8</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Mr. and Mrs. Edward P. Bass in honor of Ruth Carter Stevenson on the occasion of the reopening of the Amon Carter Museum of American Art, 2001</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Middle White Boar: Wharfedale Deliverance</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Cast by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1925</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Bronze</atom>
    <atom name="MedObjectType">Sculpture</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width
Depth
Base Height
Base Width
Base Depth</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">2 5/16
4 7/16
1 1/2
2 13/16
4 1/8
1 15/16</atom>
    <atom name="MedValueMetric_tab">5.9
11.3
3.8
7.1
10.5
4.9</atom>
    <atom name="EdiEdition">First set, 1/8 scale</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.147507]</atom>
  </tuple>

  <!-- Row 3015 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">147508</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">2001.15.9</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Mr. and Mrs. Edward P. Bass in honor of Ruth Carter Stevenson on the occasion of the reopening of the Amon Carter Museum of American Art, 2001</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Middle White Sow: Wharfedale Royal Lady</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Cast by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1925</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Bronze</atom>
    <atom name="MedObjectType">Sculpture</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width
Depth
Base Height
Base Width
Base Depth</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">2 1/2
4
1 9/16
2 13/16
3 3/16
1 15/16</atom>
    <atom name="MedValueMetric_tab">6.4
10.2
4
7.1
8.1
4.9</atom>
    <atom name="EdiEdition">First set, 1/8 scale</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.147508]</atom>
  </tuple>

  <!-- Row 3016 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">147509</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">2001.15.10</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Mr. and Mrs. Edward P. Bass in honor of Ruth Carter Stevenson on the occasion of the reopening of the Amon Carter Museum of American Art, 2001</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Percheron Mare (Messaline) and Foal</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Cast by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1925</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Bronze</atom>
    <atom name="MedObjectType">Sculpture</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width
Depth
Base Height
Base Width
Base Depth</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">5 13/16
7
2 3/4
2 5/8
5 1/8
3 1/4</atom>
    <atom name="MedValueMetric_tab">14.8
17.8
7
6.7
13
8.3</atom>
    <atom name="EdiEdition">First set, 1/8 scale</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.147509]</atom>
  </tuple>

  <!-- Row 3017 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">147510</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">2001.15.11</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Mr. and Mrs. Edward P. Bass in honor of Ruth Carter Stevenson on the occasion of the reopening of the Amon Carter Museum of American Art, 2001</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4033</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4163</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Percheron Stallion: Rhum</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Cast by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1925</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Bronze</atom>
    <atom name="MedObjectType">Sculpture</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width
Depth
Base Height
Base Width
Base Depth</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">6 3/8
2 3/16
6 1/2
2 5/16
5 15/16
3 3/16</atom>