<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    table           Group1
      integer         irn
    end
    text short      TitAccessionNo
    tuple           AccAccessionLotRef
      text long       AcqCreditLine
    end
    text long       WorAcmCollectionName
    table           CreCreatorRef_tab
      integer         irn
    end
    text long       TitMainTitle
    text long       TitParentTitle
    text long       CreRole_tab
    text long       CreType_tab
    text long       CreDateCreated_tab
    text short      MedFormat
    text long       MedMedium
    text short      MedObjectType
    text long       MedTechnique
    text long       MedType_tab
    text long       MedUnit_tab
    text long       MedUnitMetric_tab
    text long       MedValue_tab
    text long       MedValueMetric_tab
    text short      EdiEdition
    text long       RefCopyright_tab
    text long       ExhExhibitionRequirements
  end
?>
<!-- Data -->
<table name="ecatalogue">
  <!-- Row 4000 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">52654</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3555.2</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Lichen and Quartz Vein, Little Spruce Head Island, Maine, August 28, 1974</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1974</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm 
cm</atom>
    <atom name="MedValue_tab">10  7/16
7 15/16
20
15</atom>
    <atom name="MedValueMetric_tab">26.5
20.2
50.8
38.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.52654]</atom>
  </tuple>

  <!-- Row 4001 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">92393</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3557</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Fishing Boats, Bald Head, Campobello, New Brunswick, Canada, August 19, 1974</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1974</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">8
10  7/16
15
17 1/2</atom>
    <atom name="MedValueMetric_tab">20.3
26.5
38.1
44.4</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.92393]</atom>
  </tuple>

  <!-- Row 4002 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">7137</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3558</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Fishing Boats, Wilson Beach, Campobello, New Brunswick, Canada, August 19, 1974</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1974</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10  7/16
7 15/16
20
15</atom>
    <atom name="MedValueMetric_tab">26.6
20.1
50.8
38.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.7137]</atom>
  </tuple>

  <!-- Row 4003 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">23250</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3559</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Sardine Factory, Wilson Beach, Campobello, New Brunswick, Canada, August 19, 1974</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1974</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10  7/16
7 7/8
20
15</atom>
    <atom name="MedValueMetric_tab">26.6
20
50.8
38.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.23250]</atom>
  </tuple>

  <!-- Row 4004 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">27532</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3564</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Lower Dead Branches on Large Spruce, Great Spruce Head Island, Maine, July 10, 1976</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1976</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">8  1/16
10 1/8
15
18</atom>
    <atom name="MedValueMetric_tab">20.5
25.8
38.1
45.7</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.27532]</atom>
  </tuple>

  <!-- Row 4005 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">18293</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3569.2</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Bay Window, Castine, Maine, June 2, 1978</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1978</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10 3/8
8  3/16
20
15</atom>
    <atom name="MedValueMetric_tab">26.4
20.8
50.8
38.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.18293]</atom>
  </tuple>

  <!-- Row 4006 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">105827</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3587.1</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">White House with Two Locust Trees, Route 175 to Castine, Maine, June 28, 1978</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1978</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">8  5/16
10 3/8
15
17 1/2</atom>
    <atom name="MedValueMetric_tab">21.1
26.3
38.1
44.4</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.105827]</atom>
  </tuple>

  <!-- Row 4007 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">118407</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3593.1</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Dead Yellow Warbler, Great Spruce Head Island, Maine, July 12, 1978</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1978</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10  5/16
8  3/16
20
15</atom>
    <atom name="MedValueMetric_tab">26.2
20.8
50.8
38.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.118407]</atom>
  </tuple>

  <!-- Row 4008 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">124533</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3675</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Sorrel and Yarrow, Oak Island, Maine, June 26, 1982</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1982</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10  3/16
8 1/8
20
15</atom>
    <atom name="MedValueMetric_tab">25.8
20.7
50.8
38.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.124533]</atom>
  </tuple>

  <!-- Row 4009 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">89992</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3717</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Kitchen Stove, Great Spruce Head Island, Maine, July 20, 1983</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1983</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10 1/8
8  1/16
20
15</atom>
    <atom name="MedValueMetric_tab">25.7
20.5
50.8
38.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.89992]</atom>
  </tuple>

  <!-- Row 4010 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">78323</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3718</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Fireplace, Great Spruce Head Island, Maine, July 23, 1983</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1983</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10  3/16
8  1/16
20
15</atom>
    <atom name="MedValueMetric_tab">25.9
20.5
50.8
38.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.78323]</atom>
  </tuple>

  <!-- Row 4011 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">34626</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3720</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Salt Grass, Great Spruce Head Island, Maine, August 4, 1983</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1983</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10  3/16
8 1/8
20
15</atom>
    <atom name="MedValueMetric_tab">25.9
20.7
50.8
38.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.34626]</atom>
  </tuple>

  <!-- Row 4012 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">44338</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3725</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Monhegan, Maine, 1983</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1983</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">8 7/8
12 15/16
15
18</atom>
    <atom name="MedValueMetric_tab">22.5
32.9
38.1
45.7</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.44338]</atom>
  </tuple>

  <!-- Row 4013 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">108036</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3731</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Sea-eroded, Stratified Rock, Pemaquid Point, Maine, July 18, 1984</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1984</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10 1/8
8 1/8
20
15</atom>
    <atom name="MedValueMetric_tab">25.7
20.6
50.8
38.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.108036]</atom>
  </tuple>

  <!-- Row 4014 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">28274</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3738</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Sweet Peas by Farm House, Great Spruce Head Island, Maine, July 27, 1984</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1984</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10 1/8
8
20
15</atom>
    <atom name="MedValueMetric_tab">25.7
20.4
50.8
38.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.28274]</atom>
  </tuple>

  <!-- Row 4015 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">102397</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3772</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Mathias Scholle House (1822), New Harmony, Indiana, May 27, 1978</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1978</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10 1/4
8 1/8
20
15</atom>
    <atom name="MedValueMetric_tab">26
20.6
50.8
38.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.102397]</atom>
  </tuple>

  <!-- Row 4016 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">142962</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3800</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Chapel, Front View, San Miguel Viejo, Mexico, December 31, 1955</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1955</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10  3/16
7 15/16
20
15</atom>
    <atom name="MedValueMetric_tab">25.9
20.2
50.8
38.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.142962]</atom>
  </tuple>

  <!-- Row 4017 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">32486</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">P1990.51.3803</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Bequest of the artist</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Eliot Porter Bequest</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Fireworks, Queretaro, Mexico, December 25, 1955</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1955</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Dye imbibition print</atom>
    <atom name="MedObjectType">Color photographs</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Mount Height
Mount Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10  7/16
7 15/16
20
15</atom>
    <atom name="MedValueMetric_tab">26.4
20.3
50.8
38.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 1990 Amon Carter Museum of American Art</atom>