<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    table           Group1
      integer         irn
    end
    text short      TitAccessionNo
    tuple           AccAccessionLotRef
      text long       AcqCreditLine
    end
    text long       WorAcmCollectionName
    table           CreCreatorRef_tab
      integer         irn
    end
    text long       TitMainTitle
    text long       TitParentTitle
    text long       CreRole_tab
    text long       CreType_tab
    text long       CreDateCreated_tab
    text short      MedFormat
    text long       MedMedium
    text short      MedObjectType
    text long       MedTechnique
    text long       MedType_tab
    text long       MedUnit_tab
    text long       MedUnitMetric_tab
    text long       MedValue_tab
    text long       MedValueMetric_tab
    text short      EdiEdition
    text long       RefCopyright_tab
    text long       ExhExhibitionRequirements
  end
?>
<!-- Data -->
<table name="ecatalogue">


  <!-- Row 1 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">132522</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1980.49</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3374</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Great Red Tailed Hawk (Falco borealis)</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1791</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Transparent and opaque watercolor and graphite on paper</atom>
    <atom name="MedObjectType">Watercolors</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">11 1/4
8 3/4</atom>
    <atom name="MedValueMetric_tab">28.58
22.23</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.132522]</atom>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">137553</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1980.51</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3374</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Cardinal Grosbeak (Loxia cardinalis)</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1791</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Watercolor over graphite underdrawing on paper</atom>
    <atom name="MedObjectType">Watercolors</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">11 1/4
8 3/4</atom>
    <atom name="MedValueMetric_tab">28.58
22.23</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.137553]</atom>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">91012</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1980.52</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3374</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Black and White Crested Driver (Mergus cucullatus)</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1791</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Transparent and opaque watercolor and graphite on paper</atom>
    <atom name="MedObjectType">Watercolors</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">8 3/4
11 1/4</atom>
    <atom name="MedValueMetric_tab">22.23
28.58</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.91012]</atom>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">77058</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1980.53</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3374</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Red Throated Hummingbird (Troculis colubris)</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1791</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Transparent and opaque watercolor and graphite on paper</atom>
    <atom name="MedObjectType">Watercolors</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">11 3/16
8 13/16</atom>
    <atom name="MedValueMetric_tab">28.42
22.38</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.77058]</atom>
  </tuple>

  <!-- Row 5 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">132525</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1980.50</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3374</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Carolina Parrot (Psittacus carolinensis)</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1791</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Transparent and opaque watercolor and graphite on paper</atom>
    <atom name="MedObjectType">Watercolors</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">11 1/4
8 3/4</atom>
    <atom name="MedValueMetric_tab">28.58
22.23</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.132525]</atom>
  </tuple>

  <!-- Row 6 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">110104</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1980.54</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3374</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Mimic Thrush (Trudus polyglottus)</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1805-1809</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Transparent and opaque watercolor and graphite on paper</atom>
    <atom name="MedObjectType">Watercolors</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">11 3/16
8 13/16</atom>
    <atom name="MedValueMetric_tab">28.42
22.38</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.110104]</atom>
  </tuple>

  <!-- Row 7 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">76764</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1973.13</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1618</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Eastern Sioux on the Upper Mississippi</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist Attributed to</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1845</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Ink, wash, and graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">6
8
8 3/8
10 1/2</atom>
    <atom name="MedValueMetric_tab">15.4
20.3
21
26.5</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.76764]</atom>
  </tuple>

  <!-- Row 8 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">118225</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1972.116</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1838</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Grand Canyon</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1906</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Chromolithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">17 7/16
35 13/16</atom>
    <atom name="MedValueMetric_tab">44.4
91</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.118225]</atom>
  </tuple>

  <!-- Row 9 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">142201</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1967.375.1</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Ruth Carter Stevenson</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Tamarind Workshop Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Title Page (Line Involvements I)</atom>
    <atom name="TitParentTitle">[from the suite "Line Involvements"]</atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1964</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">14 3/4
20 1/16</atom>
    <atom name="MedValueMetric_tab">37.4
50.9</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 2012 The Josef and Anni Albers Foundation / Artists Rights Society (ARS), New York</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.142201]</atom>
  </tuple>

  <!-- Row 10 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">17682</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1967.375.2</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Ruth Carter Stevenson</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Tamarind Workshop Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Untitled (Line Involvements II)</atom>
    <atom name="TitParentTitle">[from the suite "Line Involvements"]</atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1964</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">19 7/8
14 5/8</atom>
    <atom name="MedValueMetric_tab">50.5
37</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 2012 The Josef and Anni Albers Foundation / Artists Rights Society (ARS), New York</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.17682]</atom>
  </tuple>

  <!-- Row 11 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">67293</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1967.375.3</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Ruth Carter Stevenson</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Tamarind Workshop Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Untitled (Line Involvements III)</atom>
    <atom name="TitParentTitle">[from the suite "Line Involvements"]</atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1964</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">14 3/4
19 7/8</atom>
    <atom name="MedValueMetric_tab">37.4
50.5</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 2012 The Josef and Anni Albers Foundation / Artists Rights Society (ARS), New York</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.67293]</atom>
  </tuple>

  <!-- Row 12 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">81386</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1967.375.4</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Ruth Carter Stevenson</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Tamarind Workshop Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Untitled (Line Involvements IV)</atom>
    <atom name="TitParentTitle">[from the suite "Line Involvements"]</atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1964</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">19 7/8
14 13/16</atom>
    <atom name="MedValueMetric_tab">50.6
37.6</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 2012 The Josef and Anni Albers Foundation / Artists Rights Society (ARS), New York</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.81386]</atom>
  </tuple>

  <!-- Row 13 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">116454</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1967.375.5</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Ruth Carter Stevenson</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Tamarind Workshop Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Untitled (Line Involvements VI)</atom>
    <atom name="TitParentTitle">[from the suite "Line Involvements"]</atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1964</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">19 7/8
14 13/16</atom>
    <atom name="MedValueMetric_tab">50.3
37.6</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 2012 The Josef and Anni Albers Foundation / Artists Rights Society (ARS), New York</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.116454]</atom>
  </tuple>

  <!-- Row 14 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">113215</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1967.375.6</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Ruth Carter Stevenson</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Tamarind Workshop Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Untitled (Line Involvements V)</atom>
    <atom name="TitParentTitle">[from the suite "Line Involvements"]</atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1964</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">14 3/4
19 13/16</atom>
    <atom name="MedValueMetric_tab">37.7
50.3</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 2012 The Josef and Anni Albers Foundation / Artists Rights Society (ARS), New York</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.113215]</atom>
  </tuple>

  <!-- Row 15 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">43953</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1967.375.7</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Ruth Carter Stevenson</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Tamarind Workshop Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Untitled (Line Involvements VII)</atom>
    <atom name="TitParentTitle">[from the suite "Line Involvements"]</atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1964</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">19 7/8
14 9/16</atom>
    <atom name="MedValueMetric_tab">50.5
37.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 2012 The Josef and Anni Albers Foundation / Artists Rights Society (ARS), New York</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.43953]</atom>
  </tuple>

  <!-- Row 16 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">122894</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1967.376.1</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Ruth Carter Stevenson</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Tamarind Workshop Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Midnight + Noon I</atom>
    <atom name="TitParentTitle">[from "Midnight and Noon, a Suite of 8 Homage to the Square"]</atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1964</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">15 3/4
15 3/4
18 7/8
20 1/2</atom>
    <atom name="MedValueMetric_tab">40
40
47.9
52.1</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 2012 The Josef and Anni Albers Foundation / Artists Rights Society (ARS), New York</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.122894]</atom>
  </tuple>

  <!-- Row 17 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">466</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1967.376.2</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Ruth Carter Stevenson</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Tamarind Workshop Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Midnight + Noon II</atom>
    <atom name="TitParentTitle">[from "Midnight and Noon, a Suite of 8 Homage to the Square"]</atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1964</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">15 3/4
15 3/4
18 7/8
20 5/8</atom>
    <atom name="MedValueMetric_tab">40
40
47.9
52.4</atom>
    <atom name="EdiEdition">20</atom>
    <atom name="RefCopyright_tab">© 2012 The Josef and Anni Albers Foundation / Artists Rights Society (ARS), New York</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.466]</atom>
  </tuple>

  <!-- Row 18 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">6869</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1967.376.3</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Ruth Carter Stevenson</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Tamarind Workshop Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Untitled (Midnight and Noon III)</atom>
    <atom name="TitParentTitle">[from "Midnight and Noon, a Suite of 8 Homage to the Square"]</atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1964</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">15 3/4
16 13/16
19
20 9/16</atom>
    <atom name="MedValueMetric_tab">40
42.7
48.3
52.2</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© 2012 The Josef and Anni Albers Foundation / Artists Rights Society (ARS), New York</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.6869]</atom>
  </tuple>

  <!-- Row 19 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">24783</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1967.376.4</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, Gift of Ruth Carter Stevenson</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Tamarind Workshop Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Untitled (Midnight and Noon IV)</atom>
    <atom name="TitParentTitle">[from "Midnight and Noon, a Suite of 8 Homage to the Square"]</atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1964</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">15 13/16
15 7/8
18 7/8
20 5/8</atom>
    <atom name="MedValueMetric_tab">40
40.3
47.9
52.4</atom>
    <atom name="EdiEdition"></atom>